import { PROJECT, validVM, validateDockerfile } from './vm-engine.mjs?v=20261009-complete';
export const LEARNING_KEY = 'docker-lab-learning-v1';
export const tasks = {
 'mental-model': { prediction:'Build และ Run แล้วแก้ index.html โดยยังไม่ Build ใหม่ หน้าเว็บใน container จะเปลี่ยนไหม?', options:['เปลี่ยนทันที','ยังเป็นหน้าเดิม'], answer:1, why:'Image เป็น snapshot; container เดิมไม่ได้อ่าน source บน host อัตโนมัติ', goal:'ใช้ Diagram: Build → Run → แก้ไฟล์เว็บโดยไม่ Build ใหม่ สังเกตว่า source เปลี่ยน แต่ image และ container ยังเป็นรุ่นเดิม', rubric:'อธิบายว่า source, image และ container ตอนนี้เก็บหน้าเว็บรุ่นใด และทำไมจึงต่างกัน', transfer:'ถ้า Run container ใหม่จาก image เดิม หลังแก้ source แต่ยังไม่ Build จะได้หน้าเว็บรุ่นไหน?', choices:['รุ่นเดิมที่อยู่ใน image','รุ่นใหม่จาก source โดยอัตโนมัติ'], correct:0 },
 cli: { prediction:'stop web แล้ว run ใหม่ด้วยชื่อ web จะเกิดอะไร?', options:['เริ่มตัวเดิม','ชื่อซ้ำ เพราะตัวเดิมยังอยู่'], answer:1, why:'stop หยุด process แต่ยังเก็บ container และชื่อไว้; start ใช้เริ่มตัวเดิม', goal:'ใน VM: รันเว็บ ส่ง request อ่าน logs แล้ว stop ให้เหลือ container ที่หยุดอยู่พร้อม log ของ request', rubric:'อธิบายความต่างของ stop, start และ rm โดยดู container ที่คุณทำไว้' },
 dockerfile: { prediction:'แก้แค่ app.js โดยวาง COPY package*.json ก่อน npm ci ขั้นติดตั้ง dependencies ต้องทำใหม่ไหม?', options:['ไม่จำเป็น หาก manifest และเงื่อนไข cache เดิมไม่เปลี่ยน','ต้องทำใหม่เสมอ'], answer:0, why:'การเปลี่ยน source หลังขั้น dependencies ไม่ทำให้ cache ของขั้นก่อนหน้าเสีย', goal:'ใน VM: เขียน Dockerfile สร้าง image แล้วรันเว็บที่แสดง index.html รุ่นปัจจุบัน ทดสอบด้วย curl ให้สำเร็จ', rubric:'อธิบายว่า build context คืออะไร และทำไมแก้ไฟล์แล้วต้อง build และสร้าง container ใหม่' },
 storage: { prediction:'rm container ที่ mount named volume แล้ว ข้อมูลใน volume ถูกลบด้วยไหม?', options:['ถูกลบพร้อมกัน','ยังอยู่ ถ้าไม่ได้ลบ volume'], answer:1, why:'Volume มีอายุแยกจาก container ต้อง mount volume เดิมกลับมาเมื่อสร้างใหม่', goal:'ใน VM: ใช้ volume ชื่อ notes เขียนข้อความลง /data/note.txt แล้วลบ container และสร้างตัวใหม่ชื่อ notes-reader โดย mount notes ที่ /data อ่านไฟล์เดิมให้ได้', rubric:'อธิบายว่าข้อมูลอยู่ที่ไหน และอะไรจะเกิดขึ้นหากเปลี่ยนชื่อ volume หรือเอา mount ออก' },
 compose: { prediction:'จาก web ใน Compose ต้องเรียกฐานข้อมูลด้วย host ใด?', options:['localhost','db'], answer:1, why:'localhost ใน web คือ web เอง ส่วน db คือชื่อ service ใน network เดียวกัน', goal:'ใน VM: ตั้ง compose.yaml ให้มี web และ db รันทั้งคู่ แล้วใช้ docker exec project-web-1 nc -z db 5432 ทดสอบการเชื่อมต่อ', rubric:'อธิบายเส้นทาง Browser → host port → web และ web → db:5432 พร้อมข้อจำกัดว่า TCP สำเร็จยังไม่ยืนยัน SQL/auth/readiness จริง' },
 workflow: { prediction:'ใช้ multi-stage แล้ว runtime ต้องมี Node และเครื่องมือ build ทั้งหมดไหม?', options:['ต้องมีทั้งหมด','ไม่ต้อง หากผลลัพธ์เป็น static files ที่ Nginx เสิร์ฟได้'], answer:1, why:'Runtime เลือกคัดลอกเฉพาะ artifact ที่ต้องใช้ ไม่จำเป็นต้องรวม build tools', goal:'ใช้ Diagram ทดลอง Build → คัดลอก dist แล้วเทียบ Watch แบบ sync กับ rebuild จากนั้นตอบโจทย์ประยุกต์ด้านล่าง', rubric:'อธิบายว่า multi-stage แก้ขนาด/องค์ประกอบ image ส่วน Watch แก้รอบการพัฒนา; sync อาจยังต้อง reload/restart แอปตามการตั้งค่า', transfer:'แก้ package-lock.json ในโปรเจกต์ Node ควรเลือก Watch action ใดเพื่อให้ติดตั้ง dependencies ใหม่?', choices:['sync ไฟล์อย่างเดียวก็พอเสมอ','rebuild image และสร้าง service ใหม่'], correct:1 },
 ship: { prediction:'ใช้ secret mount แล้วรับประกันว่า output ไม่มี secret เลยไหม?', options:['รับประกันเสมอ','ไม่ ถ้าคำสั่ง build คัดลอก secret ลง artifact เอง'], answer:1, why:'Mount ชั่วคราวไม่ป้องกันคำสั่ง build จากการเขียน secret ลงผลลัพธ์เอง', goal:'ใช้ Diagram เทียบการ mount secret กับ COPY secret แล้วตอบโจทย์ประยุกต์ด้านล่าง', rubric:'อธิบายว่าต้องตรวจทั้ง Dockerfile และ artifact และเหตุใด logs/healthcheck ยังไม่แทนการทดสอบแอปจริง', transfer:'RUN อ่าน token จาก secret mount แล้วเขียน token ลง dist/config.json แบบนี้ปลอดภัยหรือไม่?', choices:['ปลอดภัยเพราะใช้ secret mount','ไม่ปลอดภัย เพราะ token ติดไปกับ artifact'], correct:1 },
};
export function validLearning(data) {
 return !!data && typeof data==='object' && !Array.isArray(data) && Object.entries(data).every(([id,v]) => Object.hasOwn(tasks,id) && v && typeof v==='object' && !Array.isArray(v) && Object.entries(v).every(([key,value]) => ['read','practiced','task','reflected'].includes(key) ? typeof value==='boolean' : ['prediction','transfer'].includes(key) ? Number.isInteger(value)&&value>=0&&value<=1 : key==='explored' ? Array.isArray(value)&&value.length<=7&&value.every(v=>['snapshot','dist','watch-sync','watch-rebuild','watch-off','leaked','mounted'].includes(v)) : key==='reflection' ? typeof value==='string'&&value.length<=2000 : false));
}
export function lessonPassed(progress, quizCorrect) { return !!(quizCorrect && progress?.prediction!==undefined && progress?.read && progress?.practiced && progress?.task && progress?.reflected && progress?.reflection?.trim()); }
const successful = (vm,pattern,output) => vm.history.some((entry,i) => entry.kind==='command' && pattern.test(entry.text) && vm.history[i+1]?.kind==='output' && (!output || output.test(vm.history[i+1].text)));
export function checkTask(id,vm,progress={}) {
 if(tasks[id]?.transfer) { const evidence=progress.explored || []; const required=id==='mental-model'?['snapshot']:id==='workflow'?['dist','watch-sync','watch-rebuild']:['leaked','mounted']; return progress.practiced && required.every(v=>evidence.includes(v)) && progress.transfer===tasks[id].correct; }
 if(!validVM(vm)) return false;
 const containers=Object.values(vm.containers);
 if(id==='cli') return containers.some(c=>c.status==='exited'&&c.logs.some(log=>/GET \/ HTTP/.test(log))) && successful(vm,/^docker logs /);
 if(id==='dockerfile') return !validateDockerfile(vm) && containers.some(c=>c.status==='running'&&vm.images[c.tag]?.html===vm.files[`${PROJECT}/index.html`]&&c.html===vm.files[`${PROJECT}/index.html`]&&c.logs.some(log=>/GET \/ HTTP/.test(log)));
 if(id==='storage') return vm.containers['notes-reader']?.status==='running' && vm.containers['notes-reader'].mounts.some(m=>m.volume==='notes'&&m.target==='/data') && !!vm.volumeData?.notes?.['/note.txt']?.trim() && successful(vm,/^docker exec notes-reader cat \/data\/note.txt$/) && successful(vm,/^docker rm notes-writer$/);
 if(id==='compose') return containers.some(c=>c.service==='web'&&c.status==='running')&&containers.some(c=>c.service==='db'&&c.status==='running')&&successful(vm,/^docker exec project-web-1 nc -z db 5432$/, /succeeded/);
 return false;
}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderPrediction(id,p={}) {
 const t=tasks[id];
 return `<section class="learning-prediction"><span class="section-kicker">1 · ทายก่อนทดลอง</span><h2>${t.prediction}</h2><div class="learning-options">${t.options.map((o,i)=>`<button type="button" data-prediction="${i}" aria-pressed="${p.prediction===i}">${o}</button>`).join('')}</div><p role="status">${p.prediction===undefined?'เลือกคำตอบตามที่คิด แล้วใช้ Diagram ตรวจความเข้าใจ':`${p.prediction===t.answer?'ทายถูกแล้ว':'ลองสังเกตภาพอีกครั้ง'} · ${t.why}`}</p></section>`;
}
export function renderLearningTask(id,p={}) {
 const t=tasks[id];
 return `<div class="lab-card learning-guide"><span class="section-kicker">เส้นทางของบทนี้</span><h2>อ่าน → ทาย → ทดลอง → ทำเอง</h2><div class="learning-status"><span>${p.read?'✓':'○'} อ่านแล้ว</span><span>${p.practiced?'✓':'○'} ทดลอง Diagram แล้ว</span><span>${p.task?'✓':'○'} ตรวจโจทย์ผ่าน</span></div><button type="button" id="mark-read">${p.read?'อ่านแล้ว ✓':'อ่านจบแล้ว'}</button><p>2 · Diagram ในเนื้อหาใช้ทดลองแนวคิด การกดปุ่มเปลี่ยนเฉพาะภาพนี้</p><h3>3 · โจทย์ทำเอง${t.transfer?'ใน Diagram':'ใน VM Lab'}</h3><p>${t.goal}</p>${t.transfer?`<p><strong>${t.transfer}</strong></p><div class="learning-options">${t.choices.map((o,i)=>`<button type="button" data-transfer="${i}" aria-pressed="${p.transfer===i}">${o}</button>`).join('')}</div><p>บทนี้ตรวจหลักการจากแบบจำลอง ยังไม่ใช่การฝึกคำสั่งจริง</p>`:`<a class="primary-button" href="#vm?lesson=${id}">ไปทำใน VM Lab ↗</a><p>VM เก็บงานของคุณแยกจาก Diagram เมื่อทำเสร็จให้กลับมาตรวจโจทย์นี้ โดยไม่ต้อง reset งาน</p>`}<button type="button" id="check-learning-task">ตรวจโจทย์</button><p id="learning-task-feedback" role="status">${p.task?'เคยตรวจโจทย์ผ่านแล้ว ✓ · กดตรวจอีกครั้งเพื่อเช็กงานปัจจุบัน':t.transfer?'ทดลองตามโจทย์ให้ครบ แล้วเลือกคำตอบประยุกต์ก่อนตรวจ':'ตรวจจากงานปัจจุบันและประวัติ 100 รายการล่าสุด งานอื่นใน VM อาจต้องหยุดเพื่อคืนชื่อหรือพอร์ต'}</p><h3>4 · อธิบายด้วยคำของตัวเอง</h3><label for="learning-reflection">${t.rubric}</label><textarea id="learning-reflection" maxlength="2000" rows="4" placeholder="เขียนเหตุผลและสิ่งที่สังเกตได้">${escape(p.reflection)}</textarea><details><summary>แนวทางตรวจคำอธิบายตัวเอง</summary><p>${t.why} ใช้สิ่งที่เกิดขึ้นจากการทดลองยืนยันคำตอบ ไม่ใช่เพียงจำชื่อคำสั่ง</p></details><label class="learning-selfcheck"><input type="checkbox" id="learning-reflected" ${p.reflected?'checked':''}> ฉันเทียบคำอธิบายกับแนวทางแล้ว (ประเมินตัวเอง)</label><p>ตอบคำถามท้ายบทให้ถูกด้วย จึงนับว่า “ทำโจทย์ผ่าน” ไม่ใช่การรับรองความชำนาญ</p></div>`;
}
