import { renderLessonDiagram } from './lesson-diagrams.mjs?v=20261010-weeks1';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const code=(text,mode='Docker จริง · ตัวอย่างประกอบคำอธิบาย')=>`<div class="week-code-label">${mode}</div><pre class="code-block"><code>${esc(text)}</code></pre>`;
const question=(prompt,answer)=>`<details class="week-question"><summary>หยุดคิดก่อน · ${prompt}</summary><p>${answer}</p></details>`;
const scene=(id,title,body)=>({id,title,body});
export const weeks = [
 { id:'week6', number:6, date:'16 กันยายน 2026', title:'จาก Server เดิม สู่ Container แรก', topic:'Introduction to Container', source:'[INT134-G2] Class 6 Introduction to Container.docx', lead:'เริ่มจากงานเว็บที่เคยลงบน VM แล้วค่อยย้าย Frontend เข้า Container พร้อมทำความเข้าใจว่าคำสั่งแต่ละตัวกำลังจัดการอะไร', outcome:'แยก image กับ container ได้ รัน Nginx เปิดพอร์ต และอธิบาย stop / start / rm ได้', scenes:[
 scene('w6-start','ก่อนเริ่ม: งานเดิมของเรามีอะไรอยู่บ้าง?',`<p>ลองย้อนกลับไปดูงานเว็บที่เราทำมา เรามี Frontend, Backend, Database และ Reverse proxy อยู่บน Server แต่ละส่วนต้องติดตั้งโปรแกรมและตั้งค่าให้ทำงานร่วมกัน ถ้าย้ายเครื่อง เราก็ต้องเตรียมสภาพแวดล้อมอีกครั้ง</p><p>คราวนี้เราจะค่อย ๆ ย้ายทีละส่วน เริ่มที่ Frontend ก่อน เพราะดูผลผ่านหน้าเว็บได้ทันที ยังไม่ต้องย้ายทั้งระบบในครั้งเดียว เป้าหมายของคาบนี้จึงไม่ใช่จำคำสั่งให้เยอะ แต่ต้องรู้ว่าเว็บที่เปิดอยู่กำลังรันที่ไหน</p>${question('ถ้าเครื่องใหม่ไม่มี Nginx เว็บเดิมจะเปิดได้เลยไหม?','ไฟล์เว็บอย่างเดียวไม่พอ ต้องมีโปรแกรมที่เสิร์ฟไฟล์และการตั้งค่าที่เหมาะสม Container image ช่วยเตรียมส่วนนี้ให้ทำซ้ำได้')}`),
 scene('w6-image','ทำไมมี VM แล้ว ยังต้องรู้จัก Container?',`<p>VM ช่วยให้เรามีเครื่องเสมือนที่ติดตั้ง OS ของตัวเองได้ ส่วน Container แยกสภาพแวดล้อมของ process โดยใช้ kernel ของ host ร่วมกัน เราจึงไม่ต้องเตรียม guest OS เต็มชุดให้แต่ละ service</p><p>ทีนี้แยกสองคำให้ชัดก่อน: <strong>image</strong> คือแม่แบบของไฟล์และการตั้งค่า ส่วน <strong>container</strong> คือตัวที่สร้างขึ้นจากแม่แบบเพื่อรัน process หนึ่ง image จึงสร้างหลาย container ได้ และการแก้ไฟล์เฉพาะตัวหนึ่งไม่ได้เปลี่ยนแม่แบบตาม</p>${renderLessonDiagram('mental-model')}<p>ลอง Build → Run → แก้ไฟล์เว็บในภาพ สังเกตว่ารุ่นของ source ขยับ แต่ image และ container เดิมยังไม่ขยับตาม นี่คือเหตุผลที่ต่อไปเราต้องแยก “แก้ไฟล์”, “สร้าง image” และ “สร้าง container” ออกจากกัน</p>`),
 scene('w6-process','ลองรัน แล้วดูว่าอะไรทำให้มันยังอยู่',`<p>ก่อนเปิดเว็บ ลองคิดถึงโปรแกรมสั้น ๆ ที่พิมพ์ข้อความแล้วจบ ถ้า process หลักใน container ทำงานเสร็จ container ก็หยุดได้ การหยุดจึงไม่ได้แปลว่าเสียเสมอไป ต้องดูว่ารันคำสั่งอะไรและคาดหวังให้มันทำงานนานแค่ไหน</p>${code('docker run --name class-hello busybox echo hello\ndocker ps\ndocker ps -a\ndocker logs class-hello')}<p>ใน Docker จริงควรเห็นข้อความ hello และพบตัวนี้ในรายการทั้งหมด แต่ไม่ได้เป็นเว็บที่รันค้างอยู่ ตอนนี้ค่อยเปลี่ยนมารัน Nginx ซึ่งมี process สำหรับรับ request ต่อเนื่อง</p>${question('ทำไม ps ไม่เห็น แต่ ps -a เห็น?','ps แสดงตัวที่กำลังทำงาน ส่วน ps -a รวมตัวที่หยุดไปแล้วด้วย ตรวจ logs และสถานะก่อนสรุปว่าเกิด error')}`),
 scene('w6-web','เอา Frontend เข้าไป แล้วตาม request ให้ครบ',`<p>เริ่มจากหน้าเริ่มต้นของ Nginx ให้เปิดได้ก่อน เราใช้ <code>-d</code> เพื่อให้คำสั่งคืน terminal มา และใช้ <code>-p 8080:80</code> เชื่อมพอร์ตของเครื่องเข้ากับพอร์ตที่ Nginx ฟังใน container</p>${code('docker run -d --name class-web -p 8080:80 nginx:alpine\ncurl localhost:8080\ndocker logs class-web','ใช้ได้ใน VM Lab · ถ้าชื่อและพอร์ตยังว่าง')}${renderLessonDiagram('cli-port')}<p>อ่านจากฝั่งคนเปิดเว็บ: Browser เรียก host ที่พอร์ต 8080 แล้ว Docker ส่งต่อไปพอร์ต 80 ภายใน container เลขสองฝั่งทำหน้าที่ต่างกัน จึงไม่จำเป็นต้องเท่ากัน</p><p>เมื่อหน้าเริ่มต้นเปิดได้ เราค่อยนำไฟล์ Frontend ที่เตรียมไว้เข้าไปแทน ในคาบมีการใช้การคัดลอกไฟล์เพื่อให้เห็นผลก่อน ส่วนการเก็บขั้นตอนลง Dockerfile จะมาต่อใน Week 7</p>${code('docker cp ./frontend/. class-web:/usr/share/nginx/html/','Docker จริง · เตรียมโฟลเดอร์ frontend ของคุณก่อน; VM ยังไม่รองรับ docker cp')}${question('ถ้าแก้ไฟล์บน host แล้ว เว็บใน container เปลี่ยนทันทีไหม?','การ copy เป็นการคัดลอก ณ ตอนนั้น ไม่ได้เชื่อมไฟล์ให้เปลี่ยนตาม ต้อง copy ใหม่ หรือใช้วิธี mount ที่จะเรียนต่อไป')}`),
 scene('w6-life','ปิดคาบ: หยุดตัวเดิม กับสร้างตัวใหม่ต่างกันอย่างไร?',`<p>สมมติว่าเราหยุดเว็บแล้วอยากเปิดกลับมา ลองเลือกก่อนว่าจะใช้ start หรือ run ถ้าใช้ <code>start</code> เรากำลังเริ่ม container เดิม แต่ <code>run</code> ขอสร้างตัวใหม่ ชื่อเดิมจึงอาจยังถูกจองอยู่</p>${renderLessonDiagram('cli-lifecycle')}<p>ในภาพให้ Run ก่อน แล้วลอง Stop → Start แล้วดูหมายเลขตัวเดิม จากนั้น Stop → ลบ → Run แล้วสังเกตว่ากลายเป็นตัวใหม่ ไฟล์ที่อยู่เฉพาะ writable layer จะหายเมื่อลบตัวเก่า จดประเด็นนี้ไว้ เพราะ Week 7 เราจะเจอคำถามเดียวกันกับข้อมูลฐานข้อมูล</p>${question('ก่อนใช้ rm ควรถามตัวเองว่าอะไร?','ข้อมูลที่ต้องเก็บอยู่ที่ไหน หากยังอยู่เฉพาะใน container ต้องจัดเก็บให้เหมาะสมก่อนลบ; stop เพียงอย่างเดียวยังไม่ลบ writable layer')}`),
 ], practice:[['ภาพใหญ่ของ Docker','mental-model'],['คำสั่งและวงจรชีวิต','cli']], recap:['อธิบายเส้นทาง Browser → host:8080 → container:80','แยก image, container และ process หลัก','ใช้ ps -a และ logs ตรวจตัวที่หยุดได้','อธิบายได้ว่า copy ไฟล์กับ mount ไฟล์ต่างกันอย่างไร'], docs:[['Docker containers','https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/']] },
 { id:'week7',number:7,date:'23 กันยายน 2026',title:'สร้าง Image แล้วพา Database เข้ามา',topic:'Building Container Image I',source:'[INT134-G2] Class 7 Building Container Image I.docx',lead:'ต่อจาก Frontend ที่เปิดได้แล้ว เปลี่ยนงานที่ทำด้วยมือให้สร้างซ้ำได้ จากนั้นเจอปัญหาจริงของ MySQL: การตั้งค่าเริ่มต้นและข้อมูลที่ต้องอยู่ต่อ',outcome:'อธิบาย Dockerfile, การเริ่ม MySQL, bind mount และ named volume ได้ โดยไม่สับสนว่า restart policy คือการเก็บข้อมูล',scenes:[
 scene('w7-repeat','เริ่มจากคำถาม: ถ้าต้องทำ Frontend ตัวเดิมอีกรอบล่ะ?',`<p>Week 6 เรารัน Nginx แล้วนำไฟล์เข้า container ด้วยมือ วิธีนี้ช่วยให้เห็นว่าระบบทำงานอย่างไร แต่ถ้าต้องส่งงานให้เพื่อนหรือสร้างใหม่ เราต้องจำให้ได้ว่าคัดลอกอะไรไว้ตรงไหน</p><p>ให้เปลี่ยนจากจำขั้นตอนมาเขียนขั้นตอนลงไฟล์ Dockerfile ตอน build Docker จะนำ base image กับไฟล์ที่เราระบุไปสร้าง image ของเรา จากนั้นค่อย run image นั้น ขั้นตอนเตรียมเว็บจึงติดตามและทำซ้ำได้</p>${code('FROM nginx:alpine\nCOPY index.html /usr/share/nginx/html/index.html','ใช้ได้ใน VM Lab · ตัวอย่างย่อ ใช้ไฟล์ index.html ในโปรเจกต์')}<p>อ่านทีละบรรทัด: FROM เลือกแม่แบบตั้งต้น ส่วน COPY บอกว่าจะนำไฟล์อะไรจาก build context ไปไว้ใน image จุดท้ายคำสั่ง build ไม่ใช่เครื่องหมายตกแต่ง แต่ระบุตำแหน่ง context</p>${code('docker build -t my-site:1.0 .','ใช้ได้ใน VM Lab · หลังเขียน Dockerfile')}<p>ถ้าแก้ index.html หลัง build เราต้องสร้าง image ใหม่และสร้าง container จาก image ใหม่นั้นด้วย การติด tag เดิมไม่ได้ทำให้ container ที่รันอยู่เปลี่ยนตาม</p>`),
 scene('w7-db','ต่อไปลอง MySQL แล้วอ่านปัญหาจาก logs',`<p>เมื่อ Frontend มีที่อยู่ของมันแล้ว เราค่อยย้าย Database เข้ามา ในคาบนี้ใช้ <strong>MySQL 8.4</strong> ลองเริ่มจาก official image แล้วสังเกตว่าการเริ่มฐานข้อมูลต้องการการตั้งค่ามากกว่าเว็บ static</p><p>อย่ารีบแก้ด้วยการ run ซ้ำก่อนรู้เหตุ ถ้าตัวฐานข้อมูลหยุด ให้ดู ps -a และ logs เพื่อหาว่าขาดการตั้งค่าเริ่มต้นอะไร ตัวอย่างด้านล่างเลือกให้ image สร้าง root password แบบสุ่ม ตามแนวทางที่มีในคาบ</p>${code('docker run -d --name class-db -e MYSQL_RANDOM_ROOT_PASSWORD=yes mysql:8.4\ndocker logs class-db','Docker จริง · ตัวอย่าง MySQL; VM ไม่รัน MySQL')}<p>อ่าน logs จนรู้ว่าฐานข้อมูลพร้อมรับการเชื่อมต่อ และเก็บรหัสที่สร้างให้เป็นข้อมูลส่วนตัว การเห็นสถานะ running เพียงอย่างเดียวยังไม่ยืนยันว่าฐานข้อมูลเริ่มต้นเสร็จแล้ว</p>${question('ทำไมรัน Nginx ได้ทันที แต่ MySQL ต้องสนใจ environment?', 'โปรแกรมใน image แต่ละชนิดมีเงื่อนไขเริ่มต้นต่างกัน MySQL official image ใช้ค่าตั้งต้นสำหรับการ initialize ฐานข้อมูล จึงต้องอ่านเอกสารของ image และ logs')}`),
 scene('w7-mount','ข้อมูลควรอยู่ตรงไหน ถ้าต้องสร้าง Container ใหม่?',`<p>ตอนเว็บถูกลบ เรายังสร้างไฟล์จาก source ใหม่ได้ แต่ข้อมูลที่ผู้ใช้เพิ่มลงฐานข้อมูลไม่ใช่สิ่งที่ควรสร้างทิ้งแล้วเริ่มใหม่ทุกครั้ง คราวนี้จึงต้องแยกอายุของข้อมูลออกจากอายุของ container</p><p>เริ่มที่ <strong>bind mount</strong> ตามคาบ: เลือก directory บน host แล้วผูกกับ directory ข้อมูลของ MySQL ที่ <code>/var/lib/mysql</code> อีกแบบคือ <strong>named volume</strong> ให้ Docker จัดการพื้นที่เก็บ เราต้องรู้ว่ากำลังเลือกแบบไหนจากส่วนซ้ายของ mount</p>${renderLessonDiagram('week7-mount')}<p>แบบ host path เช่น <code>/srv/class/mysql:/var/lib/mysql</code> คือ bind mount ส่วน <code>class-db-data:/var/lib/mysql</code> คือ named volume ชื่อ class-db-data การใช้ <code>-v</code> เหมือนกันไม่ได้แปลว่าเป็น storage ชนิดเดียวกัน</p>${renderLessonDiagram('storage')}<p>ภาพที่เล่นได้นี้ใช้ Named volume เทียบกับ writable layer เพื่อให้เห็นอายุข้อมูล ไม่ใช่ MySQL engine และไม่ใช่แบบจำลอง bind mount ลองเขียนข้อความ ลบตัวเดิม แล้ว mount volume เดิมกลับมา</p>${question('ถ้าใช้ named volume คนละชื่อกับรอบก่อน จะเห็นข้อมูลเก่าไหม?', 'ชื่อใหม่หมายถึงคนละพื้นที่เก็บ ต้องนำพื้นที่เดิมมา mount กลับถึงจะเห็นข้อมูลเดิม และ mount ไม่ใช่ backup')}`),
 scene('w7-init','เตรียม Schema และ User ให้ทำซ้ำได้',`<p>ถ้าต้องเข้าไปสร้าง schema และ user ด้วยมือทุกครั้ง เราก็กลับไปเจอปัญหาเดิม ให้แยกสิ่งที่เป็นโครงสร้างเริ่มต้นออกมาเป็น SQL script แล้วใช้กลไก initialization ของ MySQL image</p><p>MySQL official image อ่านสคริปต์เริ่มต้นใน <code>/docker-entrypoint-initdb.d/</code> เมื่อ initialize data directory ใหม่ ตรงนี้ต้องแยกจาก directory ที่เก็บข้อมูลจริง: อันหนึ่งคือสูตรเริ่มต้น อีกอันคือข้อมูลที่เกิดขึ้นแล้ว</p><p>ลองถามต่อว่า ถ้าใช้ volume ที่มีฐานข้อมูลอยู่แล้ว แล้ว restart ทำไม script ใหม่อาจไม่ถูกเรียก? เพราะขั้น initialization ไม่ได้ทำซ้ำทุกครั้งที่ start การเปลี่ยนฐานข้อมูลที่ใช้อยู่จึงต้องมีขั้นตอน migration ที่ตั้งใจทำ</p>${question('ควรให้ Backend ใช้ root ของฐานข้อมูลเลยไหม?', 'ควรสร้าง user ของแอปและให้สิทธิ์ตามงานที่ต้องใช้ แยกบัญชีดูแลระบบออกจากบัญชีที่แอปใช้เชื่อมต่อ')}`),
 scene('w7-restart','ปิดคาบ: เปิดกลับมาได้ ไม่เท่ากับข้อมูลยังอยู่',`<p>ในคาบมีการลอง restart policy เพื่อดูว่า container จะกลับมาทำงานอย่างไรเมื่อ daemon หรือเครื่องกลับมา ให้มองเป็นอีกเรื่องหนึ่งจาก storage: policy ดูแลการเริ่ม process ส่วน mount ดูแลว่าข้อมูลอยู่ที่ไหน</p><p><code>--restart unless-stopped</code> ให้ Docker ช่วยเริ่ม container กลับตาม policy แต่ตัวที่เราสั่ง stop ไว้จะยังหยุดอยู่ แม้ Docker daemon กลับมา การตั้งค่านี้ไม่ได้สำรองข้อมูลให้เรา และไม่ได้แก้รหัสผ่านหรือ config ที่ผิด ก่อนส่งงานจึงต้องตรวจทั้งการเริ่ม service และการอ่านข้อมูลเดิมหลังสร้าง container ใหม่</p><p>สรุปเส้นทางของ Week นี้: Frontend ที่ทำด้วยมือ → Dockerfile ที่สร้างซ้ำได้ → MySQL ที่ตั้งค่าเริ่มต้นถูก → พื้นที่เก็บข้อมูลที่อยู่ต่อ สัปดาห์หน้าจะนำ Backend มาคุยกับฐานข้อมูลตัวนี้</p>`),
 ],practice:[['ฝึกสร้าง Image','dockerfile'],['ฝึกอายุของข้อมูล','storage']],recap:['อธิบาย FROM, COPY และ build context','ตรวจ logs เมื่อฐานข้อมูลเริ่มไม่ได้','แยก bind mount / named volume / writable layer','แยก init script ออกจาก data directory และ restart policy'],docs:[['MySQL official image','https://hub.docker.com/_/mysql'],['Dockerfile reference','https://docs.docker.com/reference/dockerfile/'],['Restart policy','https://docs.docker.com/engine/containers/start-containers-automatically/']] },
 {id:'week8',number:8,date:'30 กันยายน 2026',title:'พา Backend เข้ามา แล้วไล่แก้ทีละปัญหา',topic:'Building Container Image II',source:'[INT134-G2] Class 8 Building Container Image II.docx',lead:'สร้าง Image ของ Node.js แล้วตามหาสาเหตุที่ API ยังเรียกไม่ได้: ไฟล์ที่ไม่ควรเข้า image, ที่อยู่ที่แอปฟัง, ชื่อฐานข้อมูล และ process ที่ต้องรับสัญญาณหยุด',outcome:'อธิบาย build context, runtime config, user-defined network, ARG/ENV และ ENTRYPOINT/CMD ได้ พร้อมรู้ว่าอะไรต้องทดลองกับ Docker จริง',scenes:[
 scene('w8-build','เริ่มจาก Backend ที่มีอยู่ ไม่ต้องสร้างโปรเจกต์ใหม่',`<p>ตอนนี้ Frontend และ Database มี container แล้ว งานต่อไปคือ Backend เดิมของเรา ลองแยกก่อนว่าแอป Node ต้องใช้อะไร: runtime, dependencies, source code และคำสั่งเริ่มแอป เมื่อแยกได้จึงค่อยเขียน Dockerfile ตามรายการนี้</p>${code('FROM node:24-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nUSER node\nCMD ["node", "server.js"]','Docker จริง · ตัวอย่างอธิบาย ต้องมี package-lock.json และปรับชื่อไฟล์ตามแอป')}<p>WORKDIR กำหนดที่ทำงานใน image, RUN ทำงานระหว่าง build ส่วน CMD เป็นคำสั่งเริ่มต้นเมื่อ run container ลองชี้ให้ได้ว่าบรรทัดไหนเกิดตอนสร้าง image และบรรทัดไหนเกิดตอนเปิดแอป</p><p>แยกการติดตั้ง dependencies ไว้ก่อน COPY source เพื่อให้การแก้โค้ดอย่างเดียวมีโอกาสใช้ cache ของขั้นติดตั้งเดิมได้</p>${renderLessonDiagram('dockerfile')}`),
 scene('w8-context','ทำไม Context ใหญ่ และทำไมไม่ควร COPY .env?',`<p>ถ้า COPY ทั้งโฟลเดอร์โดยไม่ตรวจ อาจส่ง node_modules, .git และไฟล์ตั้งค่าส่วนตัวเข้า build context ไปด้วย การที่ build สำเร็จจึงยังไม่พอ ต้องดูด้วยว่าเราส่งอะไรไปสร้าง image</p><p>ใช้ .dockerignore คัดสิ่งที่ไม่ควรส่ง แล้วแยกค่าตั้งตอน run ออกจากตัวโปรแกรมที่สร้าง image เก็บไว้ โดยเฉพาะรหัสผ่านและ .env ของเครื่องเรา</p>${code('node_modules\n.git\n.env\n.env.*','.dockerignore · ตัวอย่างสำหรับ Docker จริง')}<p>ในคาบมีการลองดูผลหลังตัดไฟล์ออกด้วย ประเด็นที่ควรจำคือ image ควรมีสิ่งที่แอปต้องใช้ ส่วน config ของสภาพแวดล้อมควรใส่อย่างตั้งใจตอนใช้งาน ไม่ใช่ติดไปเพราะคัดลอกทั้ง directory</p>${question('เมื่อเอา .env ออกแล้ว แอปยังใช้ค่าเดิมได้เองไหม?', 'ไม่ได้ ต้องจัดค่าตั้งตอน runtime ให้แอปอ่านได้ และตรวจว่าแอปใช้ชื่อ environment หรือ path ใดจริง')}`),
 scene('w8-listen','Container รันอยู่ แต่เรียก API ไม่ได้: เริ่มตรวจตรงไหน?',`<p>ลองดู logs ก่อน ถ้า Node ฟังอยู่ที่ <code>127.0.0.1</code> ภายใน container นั่นคือ loopback ของ container เอง Request ที่เข้ามาทาง network interface จึงอาจเข้าไม่ถึง แม้ publish port ถูกแล้ว</p><p>ในคาบจึงปรับค่าที่แอปใช้ฟังให้เป็น <code>0.0.0.0</code> และตรวจ port ให้ตรงกัน ต้องแยกให้ได้ว่า bind address ของแอป กับ publish port ของ Docker เป็นคนละการตั้งค่า และแอปต้องอ่านค่าที่เราส่งให้จริง</p>${renderLessonDiagram('week8-listen')}${question('ตั้ง ENV HOST=0.0.0.0 แล้วรับประกันว่าแอปเปลี่ยนเลยไหม?', 'ไม่ ถ้าโค้ดไม่ได้อ่านตัวแปร HOST การตั้ง ENV ก็ไม่เปลี่ยนพฤติกรรม ต้องตรวจโค้ดและ logs ของแอปประกอบ')}`),
 scene('w8-network','Backend จะเรียก Database ด้วยชื่ออะไร?',`<p>ปัญหาถัดมาคือ API รันแล้ว แต่ต่อฐานข้อมูลไม่ได้ อย่าใช้ localhost โดยยังไม่ถามว่า process ที่เรียกอยู่ใน container ตัวไหน เพราะ localhost ของ Backend ไม่ใช่ Database container</p><p>ใน Week นี้ใช้ <strong>user-defined bridge network</strong> ให้ Backend กับ Database อยู่ในเครือข่ายเดียวกัน แล้วเรียกกันด้วยชื่อ container แทนการผูกกับ IP ที่อาจเปลี่ยน ถ้ามีข้อจำกัด host ของ MySQL user ต้องตรวจสิทธิ์และขอบเขตการเชื่อมต่อให้ตรงด้วย</p>${renderLessonDiagram('week8-network')}${code('docker network create class-net\ndocker network connect class-net class-db\ndocker network connect class-net class-api','Docker จริง · ต้องมี class-db และ class-api ที่รันอยู่ก่อน')}<p>หลังเชื่อม network ให้ config ของ Backend ใช้ชื่อ <code>class-db</code> และพอร์ต MySQL ภายใน <code>3306</code> แต่การหา host เจอยังไม่ยืนยันว่ารหัสผ่าน สิทธิ์ user schema หรือความพร้อมของฐานข้อมูลถูกทั้งหมด ต้องไล่จากข้อความผิดพลาดต่อ</p><p>บทฝึก Compose ในเว็บช่วยทบทวนเรื่องชื่อ service ได้ แต่เป็นเนื้อหาเสริม และใช้ PostgreSQL จำลอง; ไม่ใช่ MySQL lab ของคาบนี้</p>`),
 scene('w8-startup','ท้ายคาบ: ค่าตอน Build กับคำสั่งตอน Run',`<p>เมื่อแอปคุยกันได้แล้ว ค่อยจัดขั้นเริ่มต้นให้ชัด <strong>ARG</strong> ใช้ส่งค่าระหว่าง build ส่วน <strong>ENV</strong> ตั้ง environment ที่ส่งต่อไปยัง container ได้ ถ้าต้องการใช้ค่าจาก ARG ตอน run ต้องนำไปกำหนดต่ออย่างตั้งใจ และทั้งสองแบบไม่ควรใช้เก็บ secret ลง image</p><p>ต่อมาคือ ENTRYPOINT กับ CMD: แบบ exec form ใช้ executable กับ argument เป็นรายการ และ CMD สามารถเป็น default arguments ให้ ENTRYPOINT ได้ ส่วน shell form มี shell มาคั่น จึงต้องเข้าใจการส่ง argument และสัญญาณ process</p>${renderLessonDiagram('week8-process')}${code('# ส่วนท้าย entrypoint.sh หลังตรวจ config เสร็จ\nexec "$@"\n\n# ส่วนที่เกี่ยวข้องใน Dockerfile\n# ต้อง COPY script และกำหนด execute permission ให้เรียบร้อยก่อน\nENTRYPOINT ["./entrypoint.sh"]\nCMD ["node", "server.js"]','Docker จริง · ส่วนประกอบตัวอย่าง ไม่ใช่ Dockerfile ฉบับเต็ม')}<p>จุดที่คาบพาให้เห็นคือ เมื่อใช้ script ครอบการเริ่มแอป ต้องส่งต่อการทำงานอย่างถูกต้อง <code>exec "$@"</code> ให้ process แอปมาแทน shell แล้วแอปจึงรับสัญญาณโดยตรงได้ แต่แอปเองก็ต้องจัดการ shutdown ให้เหมาะสม</p>${question('ทำไมไม่ดูเพียงว่า run สำเร็จแล้วจบ?', 'ต้องทดสอบ request การเชื่อมฐานข้อมูล และการหยุดด้วย รวมทั้งตรวจ config และข้อมูลถาวร การรันได้ครั้งเดียวไม่ได้บอกว่าขั้น start/stop ถูกครบ')}`),
 ],practice:[['ทบทวน Build และ cache','dockerfile'],['เครือข่ายผ่าน Compose · เนื้อหาเสริม','compose'],['Security · เนื้อหาเสริม','ship']],recap:['แยก RUN กับ CMD และอธิบาย build context','ไล่ปัญหา port, bind address และ localhost','ใช้ชื่อ container ใน user-defined network และตรวจสิทธิ์ MySQL','อธิบาย ARG/ENV กับ ENTRYPOINT/CMD และการส่งสัญญาณ'],docs:[['Dockerfile reference','https://docs.docker.com/reference/dockerfile/'],['User-defined bridge network','https://docs.docker.com/engine/network/drivers/bridge/'],['MySQL official image','https://hub.docker.com/_/mysql']] },
];
export function weekNav(current) { return weeks.map(w=>`<a href="#${w.id}" class="nav-link ${current===w.id?'active':''}" ${current===w.id?'aria-current="page"':''}><span class="nav-number">W${w.number}</span><span class="nav-title">${w.title}</span></a>`).join(''); }
export function renderWeeksHome(root) {
 root.innerHTML=`<div class="lesson-page weekly-home"><span class="section-kicker">INT134 · เรียนตามคาบ</span><h1>ค่อย ๆ ย้ายเว็บ<br>เข้า Container ทีละส่วน</h1><p class="week-lead">เริ่มจากสิ่งที่ทำไว้ เจอปัญหา ลองคิด แล้วค่อยแก้ตามเหตุผล อ่านเหมือนนั่งเรียนหนึ่งคาบ พร้อม Diagram ให้ลองระหว่างทาง</p><a class="primary-button" href="#week6">เริ่ม Week 6 →</a><div class="week-cards">${weeks.map(w=>`<a href="#${w.id}" class="week-card"><span class="section-kicker">WEEK ${w.number} · ${w.date}</span><h2>${w.title}</h2><p>${w.lead}</p><strong>เข้าเรียน Week ${w.number} →</strong></a>`).join('')}</div><div class="callout"><span>ที่มาของเนื้อหา</span><p>เรียบเรียงจากเอกสารถอดเสียง Class 6–8 ของ INT134 กลุ่ม G2 เป็นคำอธิบายใหม่ ไม่ใช่คำพูดอาจารย์แบบคำต่อคำ ตัวอย่างย่อและ Diagram บางส่วนเพิ่มเพื่อช่วยทบทวน</p></div><section class="learning-bridge"><h2>อยากทบทวนเฉพาะเรื่อง?</h2><p>บทฝึกเดิมทั้ง 7 หัวข้อ พร้อม VM และความคืบหน้ายังอยู่ ใช้เป็นแบบฝึกเสริมหลังอ่านแต่ละ Week</p><a class="text-button" href="#topics">เปิดบทฝึกเสริม →</a> · <a href="#vm">เปิด VM Lab ↗</a></section><p class="week-source">มีเอกสารคาบจริงสำหรับ Week 6–8 ในชุดนี้ ส่วน Week 9 ยังไม่เพิ่มเป็นบทเรียน</p></div>`;
}
export function renderWeek(root,id) {
 const w=weeks.find(w=>w.id===id);if(!w)return false;
 const index=weeks.indexOf(w);
 root.innerHTML=`<div class="lesson-page weekly-page"><div class="lesson-breadcrumb"><a href="#home">เรียนตาม Week</a><span>/</span><span>Week ${w.number}</span></div><section class="lesson-header"><div class="lesson-number">W${w.number}</div><div><div class="lesson-meta">${w.date} · INT134 G2</div><h1>${w.title}</h1><p>${w.lead}</p></div></section><div class="week-source"><strong>เรียบเรียงตาม Class ${w.number}: ${w.topic}</strong><p>อ้างอิง ${w.source} · ถอดความและจัดย่อหน้าใหม่เพื่ออ่านง่าย ไม่ใช่คำพูดตรงของอาจารย์</p></div><div class="lesson-layout"><article class="lesson-article">${w.scenes.map((s,i)=>`<section class="text-section week-scene" id="${s.id}"><span class="section-kicker">ช่วงที่ ${i+1} / ${w.scenes.length}</span><h2>${s.title}</h2>${s.body.replace(/<figure class="lesson-diagram" data-diagram-id="([^"]+)"[\s\S]*?<\/figure>/g,(_,id)=>renderLessonDiagram(id))}</section>`).join('')}<section class="learning-bridge"><h2>ก่อนจบ Week ${w.number} ลองเล่าเอง</h2><ul>${w.recap.map(s=>`<li>${s}</li>`).join('')}</ul><p>ลองปิดคำอธิบายแล้วเล่าเหตุผล ถ้ายังติด ให้กลับไปทดลองภาพของช่วงนั้น ไม่ต้องรีบไปบทถัดไป</p></section><div class="lesson-source">ตรวจรายละเอียดเพิ่มเติม: ${w.docs.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a>`).join(' · ')}</div></article><aside class="lab-column" aria-label="แผนการเรียนราย Week"><div class="lab-card week-guide"><span class="section-kicker">วันนี้เราจะทำอะไร</span><h2>Week ${w.number}</h2><p>${w.outcome}</p><nav aria-label="ช่วงการสอน">${w.scenes.map((s,i)=>`<button type="button" data-week-scene="${s.id}"><span>0${i+1}</span>${s.title}</button>`).join('')}</nav><h3>อ่านแล้วลองทำต่อ</h3>${w.practice.map(([title,id])=>`<a href="#${id}" class="week-practice-link">${title} →</a>`).join('')}<details class="week-scope"><summary>ทดลองตรงไหนได้บ้าง?</summary><p>Diagram ในหน้านี้ทดลองแนวคิดได้ทันที โค้ดแต่ละชุดมีป้ายว่าใช้ใน VM ได้หรือใช้กับ Docker จริง VM ยังไม่รองรับ MySQL, docker cp, bind mount, network create หรือ Node runtime</p><p>การอ่าน Week ไม่เพิ่มคะแนนบทฝึกอัตโนมัติ ไปทำโจทย์ในหัวข้อที่เชื่อมไว้เพื่อเก็บความคืบหน้าบทฝึก</p></details></div></aside></div><div class="lesson-end">${index?`<a href="#${weeks[index-1].id}">← Week ${weeks[index-1].number}</a>`:'<a href="#home">← หน้าหลัก</a>'}${weeks[index+1]?`<a href="#${weeks[index+1].id}">ต่อ Week ${weeks[index+1].number} →</a>`:'<a href="#topics">ทบทวนบทฝึกเสริม →</a>'}</div></div>`;
 return true;
}
if(typeof document!=='undefined') document.addEventListener('click',event=>{
 const button=event.target.closest('[data-week-scene]');if(!button)return;
 const section=document.getElementById(button.dataset.weekScene);section?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 if(section){section.tabIndex=-1;section.focus({preventScroll:true});}
});
